### ISSUE TITLE
Error importing Werkzeug

### ISSUE THREAD

**Issue by moh55m55** [NLPbox/rst-converter-service#2]
just in case someone encountered an error in running the API . 

add Werkzeug in docker file: Werkzeug==0.16.1

**Comment by arne-cl** [comment]
Hi @moh55m55,
can you point me to a concrete error? I just build the container from scratch and ran the tests and didn't get any errors.

**Comment by moh55m55** [comment]
It has been a while. I really do not recall the error. It was an import error. Try to add --no-cache
```docker build --no-cache```

Also add "--no-cache" to the build command in this issue.
[](https://github.com/NLPbox/codra-docker/issues/5)
